on:
  push:
    branches:
          main
          
jobs:
  Docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - name: DockerInst
          shell: bash
          run: |
            sudo apt-get install ./docker-desktop-<version>-<arch>.deb
        
        - name: PyFilePic
          run: |
            docker build -t picture ./DockerExp/
            docker run picture
          
          
